# https://alacritty.org/config-alacritty.html
live_config_reload = true # 自动刷新

[env]
TERM = "alacritty"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>	"
save_to_clipboard     = true


[window]
opacity      = 0.9

# Windowed Maximized Fullscreen SimpleFullscreen
startup_mode = "Maximized"

# Values for `decorations`:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
decorations  = "None"

# 窗口内边距
padding      = { x = 4, y = 9 }


[font]
size     = 7.2
# https://github.com/alacritty/alacritty/issues/4616#issuecomment-1236413444
# defaults write -g AppleFontSmoothing -int 2
# AppleFontSmoothing  = true

[font.normal]
family   = "monospace"
style    = "Regular"

[font.italic]
family   = "monospace"
style    = "Italic"

[font.bold]
family   = "monospace"
style    = "Bold"

[font.bold_italic]
family   = "monospace"
style    = "Bold Italic"

[cursor.style]
# 光标形状 ▇ Block _ Underline | Beam
shape      = "Block"

# 光标闪烁状态
# - Never: Prevent the cursor from ever blinking
# - Off: Disable blinking by default
# - On: Enable blinking by default
# - Always: Force the cursor to always blink
blinking   = "Off"
  
[scrolling]
history    = 10000  # 回滚缓冲区的最大行数
multiplier = 3      # 一次滚动几行

[mouse]
hide_when_typing = false
